export const customers =  [
    { Id: "1",  FirstName: "Juan",  LastName: "Noria", Status: "Inactive ", Email: "juan@mydomain.com", Phone: "(234) 234-2342"},
    { Id: "2",  FirstName: "Maria",  LastName: "Montoya", Status: "Inactive ", Email: "maria@mydomain.com", Phone: "(521) 234-2342"},
    { Id: "3",  FirstName: "Ivan",  LastName: "Torres", Status: "Pending ", Email: "ivan@mydomain.com", Phone: "(255) 525-8456"},
    { Id: "4",  FirstName: "Mónica",  LastName: "Gutierrez", Status: "Active ", Email: "monica@mydomain.com", Phone:"(542) 255-5456"},
    { Id: "5",  FirstName: "Samuel",  LastName: "Gonzalez", Status: "Pending ", Email: "samuel@mydomain.com", Phone:"(255) 123-1234"},
    { Id: "6",  FirstName: "Yazmin",  LastName: "Salcedo", Status: "Active ", Email: "yazmin@mydomain.com", Phone:"(254) 234-2342"},
    { Id: "7",  FirstName: "Eva",  LastName: "Arredondo", Status: "Pending ", Email: "eva@mydomain.com", Phone:"(215) 234-2342"},
    { Id: "8",  FirstName: "Martin",  LastName: "Ruiz", Status: "Inactive ", Email: "martin@mydomain.com", Phone:"(899) 234-2342"},
    { Id: "9",  FirstName: "Carlos",  LastName: "Oliva", Status: "Inactive ", Email: "carlos@mydomain.com", Phone:"(558) 234-2342"},
    { Id: "10",  FirstName: "Eduardo",  LastName: "Encina", Status: "Active ", Email: "eduardo@mydomain.com", Phone:"(465) 234-2342"},
    { Id: "11",  FirstName: "Ramon",  LastName: "Atilano", Status: "Pending ", Email: "ramon@mydomain.com", Phone:"(461) 234-2342"},
    { Id: "12",  FirstName: "Rogelio",  LastName: "Mata", Status: "Inactive ", Email: "rogelio@mydomain.com", Phone:"(412) 234-2342"},
    { Id: "13",  FirstName: "Oscar",  LastName: "Perez", Status: "Active ", Email: "oscar@mydomain.com", Phone:"(472) 234-2342"},
    { Id: "14",  FirstName: "Jorge",  LastName: "Rodriguez", Status: "Pending ", Email: "jorge@mydomain.com", Phone:"(258) 234-2342"},
    { Id: "15",  FirstName: "Javier",  LastName: "Acosta", Status: "Active ", Email: "javier@mydomain.com", Phone:"(899) 234-2342"},
    { Id: "16",  FirstName: "Miguel",  LastName: "Alvarado", Status: "Inactive ", Email: "miguel@mydomain.com", Phone:"(123) 234-2342"},
    { Id: "17",  FirstName: "Silvia",  LastName: "Torres", Status: "Active ", Email: "silvia@mydomain.com", Phone:"(558) 234-2342"},
    { Id: "18",  FirstName: "Mariana",  LastName: "Martínez", Status: "Inactive ", Email: "mariana@mydomain.com", Phone:"(255) 234-2342"},
    { Id: "19",  FirstName: "Martin",  LastName: "Fernandez", Status: "Pending ", Email: "martin@mydomain.com", Phone:"(252) 234-2342"},  
    { Id: "20",  FirstName: "Ignacio",  LastName: "Villalba", Status: "Active ", Email: "ignacio@mydomain.com", Phone:"(889) 234-2342" }  
 ];